"""Integration tests for the FastAPI backend against real Ethiopia data and real
outputs already generated by the CLI workflows earlier in this project (verification/
significance manifests). Uses TestClient (in-process ASGI, no real network/port).
"""

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO_ROOT / "configs" / "regions" / "ethiopia.yaml"
VERIFICATION_MANIFEST = REPO_ROOT / "outputs" / "reports" / "ethiopia_verification_manifest.json"

pytestmark = pytest.mark.skipif(not CONFIG_PATH.exists(), reason="Ethiopia config not present")


@pytest.fixture(scope="module")
def client():
    import sys
    sys.path.insert(0, str(REPO_ROOT / "src"))
    from api.main import app
    return TestClient(app)


def test_health(client):
    resp = client.get("/health")
    assert resp.status_code == 200
    assert resp.json() == {"status": "ok"}


def test_list_regions_includes_ethiopia(client):
    resp = client.get("/regions")
    assert resp.status_code == 200
    names = [r["name"] for r in resp.json()]
    assert "ethiopia" in names


def test_list_regions_reports_boundary_levels(client):
    resp = client.get("/regions")
    ethiopia = next(r for r in resp.json() if r["name"] == "ethiopia")
    assert ethiopia["available_boundary_levels"] == ["admin0", "admin1", "admin2", "admin3"]


def test_get_boundary_geojson_for_each_admin_level(client):
    for level, min_features in (("admin0", 1), ("admin1", 10), ("admin2", 50), ("admin3", 500)):
        resp = client.get(f"/regions/ethiopia/boundary?level={level}")
        assert resp.status_code == 200
        body = resp.json()
        assert body["type"] == "FeatureCollection"
        assert len(body["features"]) >= min_features
        assert body["features"][0]["geometry"]["type"] in ("Polygon", "MultiPolygon")


def test_get_boundary_unknown_level_returns_404(client):
    resp = client.get("/regions/ethiopia/boundary?level=admin9")
    assert resp.status_code == 404


def test_list_indices_matches_catalog(client):
    resp = client.get("/indices")
    assert resp.status_code == 200
    names = {i["name"] for i in resp.json()}
    assert names == {"rainfall_total", "percentile", "cdd", "cwd", "dry_spell_probability", "spi"}


def test_list_forecast_systems_reports_bias_correction_provenance(client):
    resp = client.get("/forecast/systems", params={"region": "ethiopia"})
    assert resp.status_code == 200
    systems = {s["name"]: s for s in resp.json()}
    assert "seas5_operational_2026" in systems
    assert "QDM" in systems["seas5_operational_2026"]["bias_correction_method"]
    assert systems["chirps_obs"]["bias_correction_method"] == "none"


def test_list_forecast_periods_includes_known_periods(client):
    resp = client.get("/forecast/periods", params={"region": "ethiopia"})
    assert resp.status_code == 200
    labels = {p["label"] for p in resp.json()}
    assert "week1_2" in labels
    assert "JJAS" in labels
    djf = next(p for p in resp.json() if p["label"] == "DJF")
    assert djf["verifiable"] is False


def test_list_forecast_initializations_for_operational_forecast(client):
    resp = client.get("/forecast/initializations", params={"region": "ethiopia", "forecast_dataset": "seas5_operational_2026"})
    assert resp.status_code == 200
    assert resp.json() == ["2026-05-01"]


def test_list_forecast_initializations_for_hindcast_returns_33_years(client):
    resp = client.get("/forecast/initializations", params={"region": "ethiopia", "forecast_dataset": "seas5_hindcast"})
    assert resp.status_code == 200
    assert len(resp.json()) == 33


def test_unknown_region_returns_404(client):
    resp = client.get("/forecast/systems", params={"region": "nonexistent"})
    assert resp.status_code == 404


def test_climatology_periods(client):
    resp = client.get("/climatology/periods", params={"region": "ethiopia"})
    assert resp.status_code == 200
    labels = {p["label"] for p in resp.json()}
    assert "obs_1993_2025" in labels


def test_get_climatology_for_sub_seasonal_period(client):
    resp = client.get("/climatology", params={
        "region": "ethiopia", "period_type": "sub_seasonal", "period": "week1_2",
        "init_date": "2026-05-01", "climatology_period": "obs_1993_2025",
    })
    assert resp.status_code == 200
    body = resp.json()
    assert body["n_years"] == 33
    assert body["domain_mean_mm"] > 0


def test_get_climatology_missing_init_date_for_sub_seasonal_returns_400(client):
    resp = client.get("/climatology", params={"region": "ethiopia", "period_type": "sub_seasonal", "period": "week1_2"})
    assert resp.status_code == 400


def test_post_probability_percentile_below(client):
    resp = client.post("/probability", json={
        "region": "ethiopia", "init_date": "2026-05-01", "period_type": "sub_seasonal", "period": "week1_2",
        "climatology_period": "obs_1993_2025", "threshold_kind": "percentile_below", "threshold_value": 20,
    })
    assert resp.status_code == 200
    body = resp.json()
    assert 0.0 <= body["domain_mean_probability"] <= 1.0


def test_post_timeseries_returns_grid_cell_distribution(client):
    resp = client.post("/timeseries", json={
        "region": "ethiopia", "init_date": "2026-05-01", "period_type": "sub_seasonal", "period": "week1_2",
        "climatology_period": "obs_1993_2025", "lat": 9.0, "lon": 38.0,
    })
    assert resp.status_code == 200
    body = resp.json()
    assert len(body["ensemble_member_totals_mm"]) == 25
    assert len(body["historical_totals_mm"]) == len(body["historical_years"])
    assert 0.0 <= body["forecast_percentile"] <= 100.0


@pytest.mark.skipif(not VERIFICATION_MANIFEST.exists(), reason="Verification hasn't been run yet")
def test_get_verification_reads_real_manifest(client):
    resp = client.get("/verification", params={"region": "ethiopia"})
    assert resp.status_code == 200
    periods = {p["period_label"] for p in resp.json()}
    assert "week1_2" in periods
    week1_2 = next(p for p in resp.json() if p["period_label"] == "week1_2")
    assert week1_2["n_hindcast_years"] == 33
    assert any(e["label"] == "below_p20" for e in week1_2["events"])


def test_get_verification_unknown_period_404s(client):
    if not VERIFICATION_MANIFEST.exists():
        pytest.skip("Verification hasn't been run yet")
    resp = client.get("/verification", params={"region": "ethiopia", "period": "does_not_exist"})
    assert resp.status_code == 404


def test_forecast_calculate_and_poll_status(client, tmp_path, monkeypatch):
    monkeypatch.setenv("EXTREMES_OUTPUT_DIR", str(tmp_path))
    resp = client.post("/forecast/calculate", json={
        "region": "ethiopia", "forecast_dataset": "seas5_operational_2026", "observation_dataset": "chirps_obs",
        "init_date": "2026-05-01", "period_type": "sub_seasonal", "period": "week1_2", "index": "rainfall_total",
        "climatology_period": "obs_1993_2025",
    })
    assert resp.status_code == 200
    job_id = resp.json()["job_id"]
    assert resp.json()["status"] in ("pending", "running", "completed")

    import time
    for _ in range(60):
        status_resp = client.get(f"/forecast/status/{job_id}")
        assert status_resp.status_code == 200
        status = status_resp.json()
        if status["status"] in ("completed", "failed"):
            break
        time.sleep(1)

    assert status["status"] == "completed", status.get("error")
    assert "map" in status["result"]["outputs"]

    map_product_id = status["result"]["outputs"]["map"]
    map_resp = client.get(f"/maps/{map_product_id}")
    assert map_resp.status_code == 200
    assert map_resp.headers["content-type"].startswith("image/")


def test_forecast_status_unknown_job_404s(client):
    resp = client.get("/forecast/status/00000000-0000-0000-0000-000000000000")
    assert resp.status_code == 404


def test_overlay_endpoint_returns_bounded_georeferenced_png(client):
    geotiff_id = "geotiff/ethiopia_week1_2_2026-05-01_rainfall_total_median.tif"
    resp = client.get(f"/overlay/{geotiff_id}")
    assert resp.status_code == 200
    body = resp.json()
    assert len(body["bounds"]) == 4
    minlon, minlat, maxlon, maxlat = body["bounds"]
    assert maxlat > minlat  # north-up: catches the export_geotiff orientation bug if it regresses
    assert maxlon > minlon
    assert len(body["png_base64"]) > 100


def test_overlay_endpoint_rejects_non_geotiff_products(client):
    non_tif = "maps/ethiopia_week1_2_2026-05-01_rainfall_total.png"
    resp = client.get(f"/overlay/{non_tif}")
    assert resp.status_code == 400
